### ISSUE TITLE
Old version of metadata

### ISSUE THREAD

**Issue by AnAllergyToAnalogy** [mudgen/mokens-bug-bounty#4]
Your token references an out-dated version of the ERC721 Metadata extension. See the current version at the [EIP721 repo](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md).

The mutability of the `name` and `token` methods in the Metadata interface is now `view`.

**Comment by mudgen** [comment]
Hi @AnAllergyToAnalogy 

Thank you for your issue. Yes, it is correct that those methods are marked `view` in the standard and marked `pure` in my implementation.

However the standard says this:

> The above interfaces include explicit mutability guarantees for each function. Mutability guarantees are, in order weak to strong: payable, implicit nonpayable, view, and pure. Your implementation MUST meet the mutability guarantee in this interface and you MAY meet a stronger guarantee.

`pure` is a stronger mutability guarantee than `view`, so therefore it complies with the standard.

**Comment by AnAllergyToAnalogy** [comment]
You're totally right, my bad.

**Comment by mudgen** [comment]
All good.
